### PR TITLE
Update Referenda icon

### PR DESCRIPTION
**Pull request by vkulinich-cl**
Updated bell icon
Updated the index of referenda card
Updated radio button styles of rpc switcher

### CODE REVIEW

**Review by kolebjak — CHANGES_REQUESTED** [review]
There are two issues with this: 

1. Bell no loger rotates on hover - not sure if that's intentional or not
2. There's no background effect if you hover over the star - you get it if you hover over the bell itself. 

 

https://github.com/galacticcouncil/HydraDX-ui/assets/19366687/8f182ff5-390c-4445-bdf6-795ba24fce59

**Comment by vkulinich-cl** [comment]
> There are two issues with this:
> 
> 1. Bell no loger rotates on hover - not sure if that's intentional or not
> 2. There's no background effect if you hover over the star - you get it if you hover over the bell itself.
> 
>  Screen.Recording.2023-07-19.at.12.43.04.mov

1. Yes it should rotate on the click only, it was required by design
2. Will change it

**Comment by kolebjak** [comment]
https://github.com/galacticcouncil/HydraDX-ui/assets/19366687/9780e79c-f7a5-4f39-96f4-0facff60de1d

@vkulinich-cl still acting a bit weird with icon color

**Comment by vkulinich-cl** [comment]
> Screen.Recording.2023-07-19.at.14.59.46.mov 
> @vkulinich-cl still acting a bit weird with icon color

done

**Review by kolebjak — APPROVED** [review]
🚀

**Pull request merged**
