### PR TITLE
feat(#147): Added link to subscan in notification center

### PR DESCRIPTION
**Pull request by tomashapl1**

### CODE REVIEW

**Comment by jak-pan** [comment]
https://deploy-preview-170--edge-hydra-app.netlify.app/#/trade don't see this here. Is it behind some flag?

**Review by vkulinich-cl — APPROVED** [review]

**Comment by jak-pan** [comment]
I think we had the problem with wrong ID used here and we followed up on this but I don't see new commits here. Did we just forget about this?

**Comment by tomashapl1** [comment]
> I think we had the problem with wrong ID used here and we followed up on this but I don't see new commits here. Did we just forget about this?

Yes, we were waiting for release trade app

**Comment by tomashapl1** [comment]
@jak-pan you can check it there: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-hydradx-rpc.hydration.dev#/explorer/query/748032 on rococo

**Review by jak-pan — APPROVED** [review]

**Comment by jak-pan** [comment]
> @jak-pan you can check it there: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-hydradx-rpc.hydration.dev#/explorer/query/748032 on rococo
> 
> with correct index:
> 
> image

Works. U can check it on mainnet with some small tx by using edge-app preview

**Pull request merged**
